name: local_dictionary_api
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dictionary_api: 0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/dictionary.json
